---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-with-ovirt-credentials
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.ovirt-engine-server/ovirt-engine/api/"
    username: admin@internal # provided in the format of username@domain
    password: 123456
    ca.cert: | # The certificate presented by the server will be verified using these CA certificates.
               # If not set, system wide CA certificate store is used. Expected in base64 format.
    -----BEGIN CERTIFICATE-----
    MIIDCjCCAfKgAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MTQwMgYDVQQDDCtvcGVu
    c2hpZnQtc2VydmljZS1zZXJ2aW5nLXNpZ25lckAxNTc4MTE2ODE5MB4XDTIwMDEw
    NDA1NDY1OVoXDTIxMDEwMzA1NDcwMFowNjE0MDIGA1UEAwwrb3BlbnNoaWZ0LXNl
    cnZpY2Utc2VydmluZy1zaWduZXJAMTU3ODExNjgxOTCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAMbvNJ4Z59E26HfzxAKVqQuN99hE/4zDSZ52bVgcQIsD
    d9xwuOdHUGog8GQDHZRUBUtxYFdy6OG0i/UbUvNKXbC/UQ7vGfIZ44xoCNcQTVdO
    je5VSnto5eWBA5cwfaRH3MvOKhhkYU/3l2+j0JzPB40Jz5KpwCwoIgwQ6eSmffeS
    7EuREWZcEtaRnbmewwWenhYK9LnLb2Esapbl23xuPe5B1GrSNWve33/syooh1p/f
    rzIvn2liw+GT9L+/hNPQxq/9Naj6kIiXt6aNzg9A0sZ7r2dDpM78I4TDWA3KsZ1s
    Rimc0I8/KNryxNYGPZ6UhXu+3+Q2sHPD89HID6QYXTcCAwEAAaMjMCEwDgYDVR0P
    AQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJw3
    JI5dC/QwLHkzAaGyQConsoE8q5NYWUZqV7R6IlqWR5hgfVK30RY2W/o9FK+lUMuE
    0yz95diEBNq7+02rr/xcvlrgao11vM+Sngh8cbdUdHvbrG8MWVmzzf2LFxixV1Ym
    We3q3QMkwH3s7uWrZSUmSX15dD7TO/JY8w6r5rwJQB3ddlNHBal9kLoKSTcaFnB9
    v/ac3DWToOKI5K4YYj8JnTnuRGiC98bzRNJXY6a1askw9v0Z3qiw+dtplV7GElLn
    c02i80fMjPco20yQ0Iz+Tw4EASEs4Qows5GX5YP5B4adq3Ke6NVod15ucDBKTYyH
    4aWp9HxgR0td6kLu3FQ=
    -----END CERTIFICATE-----
    insecure: true # Indicates if the server TLS certificate and host name should be checked
